---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-crossplane
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: crossplane-terraform
    repoURL: 'https://github.com/arun12cool/tf.git//crossplane-argocd'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

