---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-install
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: crossplane-terraform
    repoURL: 'https://github.com/arun12cool/tf.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

